name: do-the-job
on: push
jobs:

  do-the-job:
    name: Do the job on the runner
    runs-on: i-031db0cc9aa38678f
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Hello World
        run: echo 'Hello World!'
 
